### ISSUE TITLE
Plugin review issues

### ISSUE THREAD

**Issue by iv-enovation** [eLearning-BS23/moodle-availability_sslcommerz#13]
Hi, 

please find the list below - i put everything in 1 issue

* In all php files direct access to $_POST must be rewritten to optional_param() or required_param() unless not possible, but then a clear explanation why not possible is needed;
* please use Moodle's curl implementation
* please always set CURLOPT_SSL_VERIFYPEER to true for production code
* hardcoded string literals are acceptable for errors - but please reconsider if in some places (when reporting success) get_string() should be used instead

### cancel.php:
- why "use mod_lti\local\ltiservice\response;" ? and if it's needed, the plugin must be declared dependent on mld_lti in version.php
- direct access to $_POST
- a hardcoded literal used, for an error though. $_POST['value_d'] passed directly to URL, potential insertion vulnerability

### checkout.php:
- direct access to $_POST;
- PHP's curl is used instead of Moodle's curl;
- CURLOPT_SSL_VERIFYPEER false !!!!

classes/transactions_table.php:
- completely commented out file, should be removed from the plugin

### fail.php:
- same as in cancel.php

### ipn.php:
- set_exception_handler(\availability_sslcommerz\util::get_exception_handler()); - but i cannot find class util, neither function get_exception_handler()
- direct access to $_POST
- PHP's curl used instead of Moodle's
- CURLOPT_SSL_VERIFYHOST false !!!
- $amount and $currency not used
- \enrol_sslcommerz\util::message_sslcommerz_error_to_admin() used - but the plugin itself is not declared as dependent on enrol_sslcommerz
- hardcoded literal: echo "Payment was Cancelled"; - this does not look like an error

### lib.php:
- new moodle_url('/availability/condition/sslcommerz/transactions.php', ['courseid' => $course->id]), - the URL does not seem existing

### return.php:
- again use mod_lti\local\ltiservice\response;
- direct access to $_POST
- PHP's curl used;
- CURLOPT_SSL_VERIFYPEER false !!!
- foreach ($_POST as $key => $value) {
        if ($key !== clean_param($key, PARAM_ALPHANUMEXT)) { <-values are still not sanitized
- $plugin = enrol_get_plugin('sslcommerz'); -> ah??
- $existing = $DB->get_record("enrol_sslcommerz",
- \enrol_sslcommerz\util::message_sslcommerz_error_to_admin
ACTUALLY - is this file ever used? it seems to be a copy from enrol_sslcommerz and might be completely not needed in this plugin

### success.php:
- use mod_lti\local\ltiservice\response;
- direct access to $_POST
- $DB->insert_record("availability_sslcommerz_tnx", $data); $data is formed from $_POST - very prominent sql injection possibility
- $_POST['value_d'] appended directly to URL

**Comment by nawazsharif** [comment]
issue solved
